### ISSUE TITLE
Question: Does the lovelace_gen working for you in v2022.7 ?

### ISSUE THREAD

**Issue by Idan37S** [theone11/HomeAssistantConfig#1]
Hi,

First, I want to say thanks for sharing your amazing setup which I helped me so much during my floorplan setup.
Second, I wanted to ask you if you were able to use lovelace_gen in 2022.7  with your floorplan?

**Comment by theone11** [comment]
No problem using HA 2022.7.6

**Comment by Idan37S** [comment]
Did you had to make any special changes or did it just worked?

**Comment by theone11** [comment]
No changes.
What exactly is the problem you get?

**Comment by Idan37S** [comment]
I'm getting Unknow Error for some reason.
Thanks anyway.

**Comment by theone11** [comment]
Look in the log file

**Comment by theone11** [comment]
Works fine
